#############################################################################
# Makefile for building: MusicStop
# Generated by qmake (2.01a) (Qt 4.7.4) on: ?? 10. ??? 20:23:32 2012
# Project:  MusicStop.pro
# Template: app
# Command: d:\symbian\qtsdk\symbian\sdks\symbiansr1qt474\bin\qmake.exe -spec ..\..\Symbian\SDKs\SymbianSR1Qt474\mkspecs\symbian-sbsv2 CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o bld.inf MusicStop.pro
#############################################################################

MAKEFILE          = Makefile
QMAKE             = d:\symbian\qtsdk\symbian\sdks\symbiansr1qt474\bin\qmake.exe
DEL_FILE          = del /q 2> NUL
DEL_DIR           = rmdir
CHK_DIR_EXISTS    = if not exist
MKDIR             = mkdir
MOVE              = move
DEBUG_PLATFORMS   = winscw gcce armv5 armv6
RELEASE_PLATFORMS = gcce armv5 armv6
MAKE              = make
SBS               = sbs

DEFINES	 = -DSYMBIAN -DUNICODE -DQT_KEYPAD_NAVIGATION -DQT_SOFTKEYS_ENABLED -DQT_USE_MATH_H_FLOATS -DQ_COMPONENTS_SYMBIAN -DQT_NO_DEBUG -DQT_DECLARATIVE_LIB -DQT_GUI_LIB -DQT_CORE_LIB
INCPATH	 =  -I"D:/Symbian/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include/QtCore"  -I"D:/Symbian/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include/QtGui"  -I"D:/Symbian/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include/QtDeclarative"  -I"D:/Symbian/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include"  -I"D:/Symbian/QtSDK/Symbian/SDKs/SymbianSR1Qt474/mkspecs/common/symbian"  -I"D:/Symbian/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include"  -I"D:/Symbian/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/stdapis"  -I"D:/Symbian/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/stdapis/sys"  -I"D:/Symbian/QtSDK/workspace/MusicStop/qmlapplicationviewer"  -I"D:/Symbian/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/stdapis/stlportv5"  -I"D:/Symbian/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/mw"  -I"D:/Symbian/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/mw"  -I"D:/Symbian/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform"  -I"D:/Symbian/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/loc"  -I"D:/Symbian/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/mw/loc"  -I"D:/Symbian/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/loc/sc"  -I"D:/Symbian/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/mw/loc/sc"  -I"D:/Symbian/QtSDK/workspace/MusicStop/moc"  -I"D:/Symbian/QtSDK/workspace/MusicStop"  -I"D:/Symbian/QtSDK/workspace/MusicStop/ui" 
first: default

all: debug release

default: debug-winscw
qmake:
	$(QMAKE) "D:/Symbian/QtSDK/workspace/MusicStop/MusicStop.pro"  -spec ..\..\Symbian\SDKs\SymbianSR1Qt474\mkspecs\symbian-sbsv2 CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

bld.inf: D:/Symbian/QtSDK/workspace/MusicStop/MusicStop.pro
	$(QMAKE) "D:/Symbian/QtSDK/workspace/MusicStop/MusicStop.pro"  -spec ..\..\Symbian\SDKs\SymbianSR1Qt474\mkspecs\symbian-sbsv2 CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

d:\Symbian\QtSDK\workspace\MusicStop\MusicStop.loc: 
	$(QMAKE) "D:/Symbian/QtSDK/workspace/MusicStop/MusicStop.pro"  -spec ..\..\Symbian\SDKs\SymbianSR1Qt474\mkspecs\symbian-sbsv2 CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

debug: d:\Symbian\QtSDK\workspace\MusicStop\MusicStop.loc bld.inf
	$(SBS) -c winscw_udeb.mwccinc -c armv5_udeb -c armv6_udeb
clean-debug: bld.inf
	$(SBS) reallyclean --toolcheck=off -c winscw_udeb.mwccinc -c armv5_udeb -c armv6_udeb
freeze-debug: bld.inf
	$(SBS) freeze -c winscw_udeb.mwccinc -c armv5_udeb -c armv6_udeb
release: d:\Symbian\QtSDK\workspace\MusicStop\MusicStop.loc bld.inf
	$(SBS) -c armv5_urel -c armv6_urel
clean-release: bld.inf
	$(SBS) reallyclean --toolcheck=off -c armv5_urel -c armv6_urel
freeze-release: bld.inf
	$(SBS) freeze -c armv5_urel -c armv6_urel

debug-winscw: d:\Symbian\QtSDK\workspace\MusicStop\MusicStop.loc bld.inf
	$(SBS) -c winscw_udeb.mwccinc
clean-debug-winscw: bld.inf
	$(SBS) reallyclean -c winscw_udeb.mwccinc
freeze-debug-winscw: bld.inf
	$(SBS) freeze -c winscw_udeb.mwccinc
debug-gcce: d:\Symbian\QtSDK\workspace\MusicStop\MusicStop.loc bld.inf
	$(SBS) -c arm.v5.udeb.gcce4_4_1
clean-debug-gcce: bld.inf
	$(SBS) reallyclean -c arm.v5.udeb.gcce4_4_1
freeze-debug-gcce: bld.inf
	$(SBS) freeze -c arm.v5.udeb.gcce4_4_1
debug-armv5: d:\Symbian\QtSDK\workspace\MusicStop\MusicStop.loc bld.inf
	$(SBS) -c armv5_udeb
clean-debug-armv5: bld.inf
	$(SBS) reallyclean -c armv5_udeb
freeze-debug-armv5: bld.inf
	$(SBS) freeze -c armv5_udeb
debug-armv6: d:\Symbian\QtSDK\workspace\MusicStop\MusicStop.loc bld.inf
	$(SBS) -c armv6_udeb
clean-debug-armv6: bld.inf
	$(SBS) reallyclean -c armv6_udeb
freeze-debug-armv6: bld.inf
	$(SBS) freeze -c armv6_udeb
release-gcce: d:\Symbian\QtSDK\workspace\MusicStop\MusicStop.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1
clean-release-gcce: bld.inf
	$(SBS) reallyclean -c arm.v5.urel.gcce4_4_1
freeze-release-gcce: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1
release-armv5: d:\Symbian\QtSDK\workspace\MusicStop\MusicStop.loc bld.inf
	$(SBS) -c armv5_urel
clean-release-armv5: bld.inf
	$(SBS) reallyclean -c armv5_urel
freeze-release-armv5: bld.inf
	$(SBS) freeze -c armv5_urel
release-armv6: d:\Symbian\QtSDK\workspace\MusicStop\MusicStop.loc bld.inf
	$(SBS) -c armv6_urel
clean-release-armv6: bld.inf
	$(SBS) reallyclean -c armv6_urel
freeze-release-armv6: bld.inf
	$(SBS) freeze -c armv6_urel
debug-armv5-rvct2.2: d:\Symbian\QtSDK\workspace\MusicStop\MusicStop.loc bld.inf
	$(SBS) -c arm.v5.udeb.rvct2_2
clean-debug-armv5-rvct2.2: bld.inf
	$(SBS) reallyclean -c arm.v5.udeb.rvct2_2
freeze-debug-armv5-rvct2.2: bld.inf
	$(SBS) freeze -c arm.v5.udeb.rvct2_2
release-armv5-rvct2.2: d:\Symbian\QtSDK\workspace\MusicStop\MusicStop.loc bld.inf
	$(SBS) -c arm.v5.urel.rvct2_2
clean-release-armv5-rvct2.2: bld.inf
	$(SBS) reallyclean -c arm.v5.urel.rvct2_2
freeze-release-armv5-rvct2.2: bld.inf
	$(SBS) freeze -c arm.v5.urel.rvct2_2
debug-armv5-gcce4.4.1: d:\Symbian\QtSDK\workspace\MusicStop\MusicStop.loc bld.inf
	$(SBS) -c arm.v5.udeb.gcce4_4_1
clean-debug-armv5-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v5.udeb.gcce4_4_1
freeze-debug-armv5-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v5.udeb.gcce4_4_1
release-armv5-gcce4.4.1: d:\Symbian\QtSDK\workspace\MusicStop\MusicStop.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1
clean-release-armv5-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v5.urel.gcce4_4_1
freeze-release-armv5-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1
debug-armv6-rvct2.2: d:\Symbian\QtSDK\workspace\MusicStop\MusicStop.loc bld.inf
	$(SBS) -c arm.v6.udeb.rvct2_2
clean-debug-armv6-rvct2.2: bld.inf
	$(SBS) reallyclean -c arm.v6.udeb.rvct2_2
freeze-debug-armv6-rvct2.2: bld.inf
	$(SBS) freeze -c arm.v6.udeb.rvct2_2
release-armv6-rvct2.2: d:\Symbian\QtSDK\workspace\MusicStop\MusicStop.loc bld.inf
	$(SBS) -c arm.v6.urel.rvct2_2
clean-release-armv6-rvct2.2: bld.inf
	$(SBS) reallyclean -c arm.v6.urel.rvct2_2
freeze-release-armv6-rvct2.2: bld.inf
	$(SBS) freeze -c arm.v6.urel.rvct2_2
debug-armv6-gcce4.4.1: d:\Symbian\QtSDK\workspace\MusicStop\MusicStop.loc bld.inf
	$(SBS) -c arm.v6.udeb.gcce4_4_1
clean-debug-armv6-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v6.udeb.gcce4_4_1
freeze-debug-armv6-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v6.udeb.gcce4_4_1
release-armv6-gcce4.4.1: d:\Symbian\QtSDK\workspace\MusicStop\MusicStop.loc bld.inf
	$(SBS) -c arm.v6.urel.gcce4_4_1
clean-release-armv6-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v6.urel.gcce4_4_1
freeze-release-armv6-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v6.urel.gcce4_4_1

export: bld.inf
	$(SBS) export -c winscw_udeb.mwccinc -c armv5_udeb -c armv6_udeb -c armv5_urel -c armv6_urel

cleanexport: bld.inf
	$(SBS) cleanexport -c winscw_udeb.mwccinc -c armv5_udeb -c armv6_udeb -c armv5_urel -c armv6_urel

freeze: freeze-release

check: first

run:
	call D:/Symbian/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/release/winscw/udeb/MusicStop.exe $(QT_RUN_OPTIONS)

runonphone: sis
	runonphone $(QT_RUN_ON_PHONE_OPTIONS) --sis MusicStop.sis MusicStop.exe $(QT_RUN_OPTIONS)

MusicStop_template.pkg: D:/Symbian/QtSDK/workspace/MusicStop/MusicStop.pro
	$(MAKE) -f $(MAKEFILE) qmake

MusicStop_installer.pkg: D:/Symbian/QtSDK/workspace/MusicStop/MusicStop.pro
	$(MAKE) -f $(MAKEFILE) qmake

MusicStop_stub.pkg: D:/Symbian/QtSDK/workspace/MusicStop/MusicStop.pro
	$(MAKE) -f $(MAKEFILE) qmake

sis: MusicStop_template.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_sis:
	D:\Symbian\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat -g $(QT_SIS_OPTIONS) MusicStop_template.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

unsigned_sis: MusicStop_template.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_unsigned_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_unsigned_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_unsigned_sis:
	D:\Symbian\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat -g $(QT_SIS_OPTIONS) -o MusicStop_template.pkg $(QT_SIS_TARGET)

MusicStop.sis:
	$(MAKE) -f $(MAKEFILE) sis

installer_sis: MusicStop_installer.pkg sis
	$(MAKE) -f $(MAKEFILE) ok_installer_sis

ok_installer_sis: MusicStop_installer.pkg
	D:\Symbian\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat $(QT_SIS_OPTIONS) MusicStop_installer.pkg - $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

unsigned_installer_sis: MusicStop_installer.pkg unsigned_sis
	$(MAKE) -f $(MAKEFILE) ok_unsigned_installer_sis

ok_unsigned_installer_sis: MusicStop_installer.pkg
	D:\Symbian\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat $(QT_SIS_OPTIONS) -o MusicStop_installer.pkg

fail_sis_nocache:
	$(error Project has to be built or QT_SIS_TARGET environment variable has to be set before calling 'SIS' target)

stub_sis: MusicStop_stub.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_stub_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_stub_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_stub_sis:
	D:\Symbian\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat -s $(QT_SIS_OPTIONS) MusicStop_stub.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

deploy: sis
	call MusicStop.sis

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc\moc_qmlapplicationviewer.cpp moc\moc_localizer.cpp moc\moc_application.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc\moc_qmlapplicationviewer.cpp moc\moc_localizer.cpp moc\moc_application.cpp
moc\moc_qmlapplicationviewer.cpp: qmlapplicationviewer\qmlapplicationviewer.h
	D:\Symbian\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN d:\Symbian\QtSDK\workspace\MusicStop\qmlapplicationviewer\qmlapplicationviewer.h -o d:\Symbian\QtSDK\workspace\MusicStop\moc\moc_qmlapplicationviewer.cpp

moc\moc_localizer.cpp: localizer.h
	D:\Symbian\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN d:\Symbian\QtSDK\workspace\MusicStop\localizer.h -o d:\Symbian\QtSDK\workspace\MusicStop\moc\moc_localizer.cpp

moc\moc_application.cpp: localizer.h \
		application.h
	D:\Symbian\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN d:\Symbian\QtSDK\workspace\MusicStop\application.h -o d:\Symbian\QtSDK\workspace\MusicStop\moc\moc_application.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: ui\qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) ui\qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

dodistclean:
	-@ if EXIST "d:\Symbian\QtSDK\workspace\MusicStop\MusicStop_template.pkg" $(DEL_FILE)  "d:\Symbian\QtSDK\workspace\MusicStop\MusicStop_template.pkg"
	-@ if EXIST "d:\Symbian\QtSDK\workspace\MusicStop\MusicStop_stub.pkg" $(DEL_FILE)  "d:\Symbian\QtSDK\workspace\MusicStop\MusicStop_stub.pkg"
	-@ if EXIST "d:\Symbian\QtSDK\workspace\MusicStop\MusicStop_installer.pkg" $(DEL_FILE)  "d:\Symbian\QtSDK\workspace\MusicStop\MusicStop_installer.pkg"
	-@ if EXIST "d:\Symbian\QtSDK\workspace\MusicStop\Makefile" $(DEL_FILE)  "d:\Symbian\QtSDK\workspace\MusicStop\Makefile"
	-@ if EXIST "d:\Symbian\QtSDK\workspace\MusicStop\MusicStop_exe.mmp" $(DEL_FILE)  "d:\Symbian\QtSDK\workspace\MusicStop\MusicStop_exe.mmp"
	-@ if EXIST "d:\Symbian\QtSDK\workspace\MusicStop\MusicStop_reg.rss" $(DEL_FILE)  "d:\Symbian\QtSDK\workspace\MusicStop\MusicStop_reg.rss"
	-@ if EXIST "d:\Symbian\QtSDK\workspace\MusicStop\MusicStop.rss" $(DEL_FILE)  "d:\Symbian\QtSDK\workspace\MusicStop\MusicStop.rss"
	-@ if EXIST "d:\Symbian\QtSDK\workspace\MusicStop\MusicStop.loc" $(DEL_FILE)  "d:\Symbian\QtSDK\workspace\MusicStop\MusicStop.loc"
	-@ if EXIST "d:\Symbian\QtSDK\workspace\MusicStop\bld.inf" $(DEL_FILE)  "d:\Symbian\QtSDK\workspace\MusicStop\bld.inf"

distclean: clean dodistclean

clean: bld.inf
	-$(SBS) reallyclean --toolcheck=off -c winscw_udeb.mwccinc -c armv5_udeb -c armv6_udeb -c armv5_urel -c armv6_urel


